Refactor variable checks in workflow to ensure required repository variables are set

diff --git a/.github/workflows/build.docker.images.yml b/.github/workflows/build.docker.images.yml
--- a/.github/workflows/build.docker.images.yml
+++ b/.github/workflows/build.docker.images.yml
@@ -37,30 +37,41 @@ env:
   SOFTWARE_BUILD: ${{ inputs.softwarebuild }}
 
 jobs:
-  requirements:
-    name: Requirements
-    runs-on: ubuntu-latest
+  set-variables:
+    name: Set-Variables
+    runs-on: ubuntu-slim
 
-    strategy:
-      fail-fast: false
-      matrix:
-        vars: [REGISTRY, REGISTRY_ACCOUNT, REGISTRY_REPO, REGISTRY_REPO_TAG_CACHE_NAME, REGISTRY_PLATFORMS]
+    permissions:
+      contents: read
 
     steps:
-      - name: Check if variable exist
+      - name: Check required variables
+        shell: bash
         run: |
-          if [[ -z ${!VARNAME} ]]; then
-            echo "Variable \"${VARNAME}\" not found. Please create the variable under \"Repository variables\" \(https://github.com/${{ github.REPOSITORY}}/settings/variables/actions\)."
-            exit 1
-          fi
-        env:
-          VARNAME: "${{ matrix.vars }}"
+          missing=0
+
+          for var in \
+            REGISTRY \
+            REGISTRY_ACCOUNT \
+            REGISTRY_REPO \
+            REGISTRY_REPO_TAG_CACHE_NAME \
+            REGISTRY_PLATFORMS
+          do
+            if [[ -z "${!var}" ]]; then
+              echo "::error::Repository variable '$var' is missing."
+              missing=1
+            else
+              echo "::notice::$var is configured."
+            fi
+          done
+
+          exit $missing
 
   setup-build-push:
     name: Docker build & push
     runs-on: ubuntu-latest
     needs:
-      - requirements
+      - set-variables
 
     steps:
       - name: Checkout
